USE Farm_Management_Shevchenko;
GO

DECLARE @sql NVARCHAR(MAX) = '';

SELECT @sql = @sql + 'ALTER TABLE ' + QUOTENAME(SCHEMA_NAME(schema_id)) + '.' + QUOTENAME(OBJECT_NAME(parent_object_id)) + ' DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13)
FROM sys.foreign_keys;

EXEC sp_executesql @sql;

IF OBJECT_ID('FERTILIZER_APPLICATION', 'U') IS NOT NULL DROP TABLE FERTILIZER_APPLICATION;
IF OBJECT_ID('WORKER_EQUIPMENT_SKILL', 'U') IS NOT NULL DROP TABLE WORKER_EQUIPMENT_SKILL;
IF OBJECT_ID('WORKER', 'U') IS NOT NULL DROP TABLE WORKER;
IF OBJECT_ID('EQUIPMENT', 'U') IS NOT NULL DROP TABLE EQUIPMENT;
IF OBJECT_ID('LAND_PLOT', 'U') IS NOT NULL DROP TABLE LAND_PLOT;
IF OBJECT_ID('FERTILIZER', 'U') IS NOT NULL DROP TABLE FERTILIZER;
IF OBJECT_ID('CROP', 'U') IS NOT NULL DROP TABLE CROP;
IF OBJECT_ID('BRIGADE', 'U') IS NOT NULL DROP TABLE BRIGADE;